
name: Check Stock

on:
  workflow_dispatch:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: ファイルを取得
        uses: actions/checkout@v4

      - name: Pythonを準備
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 必要なものをインストール
        run: pip install requests beautifulsoup4

      - name: 在庫チェック
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python stock.py
